sudo: required

language: ruby

services:
  - docker

before_install:
  - cd integration_test/
  - ./prepare.sh
  - docker-compose build

script:
  - docker-compose up -d
  - docker-compose logs -f test | tail -n 2 | grep 'code 0'
