version: '2'
services:
  log:
    build:
      context: .
      dockerfile: Dockerfile.log
    restart: always
    volumes:
      - /var/log/shelter/:/var/log/docker/
    ports:
      - 1514:514
  registry:
    image: library/registry:2.4.0
    restart: always
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  db:
    image: postgres
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "db"
  redis:
    image: redis
    ports:
      - 6380:6379
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "redis"
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # sleep 3 seconds in order to wait db start up
    command: bash -c 'sleep 3 && bundle install && bundle exec sidekiq'
    environment:
      RAILS_ENV: production
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis/0
    volumes:
      - .:/shelter
    depends_on:
      - db
      - registry
      - redis
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "worker"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    # sleep 3 seconds first to wait db start up
    command: bash -c 'sleep 3 && bundle install && bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0'
    environment:
      RAILS_ENV: production
    volumes:
      - .:/shelter
    depends_on:
      - log
      - db
      - registry
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "web"
  proxy:
    image: nginx:1.9
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - log
      - db
      - registry
      - web
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"