version: '2'
services:
  registry:
    image: library/registry:2.4.0
    restart: always
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
  db:
    image: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    command: bash -c 'bundle install && bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0'
    volumes:
      - .:/shelter
    depends_on:
      - db
      - registry
  proxy:
    image: nginx:1.9
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - registry
      - app
