version: '2'
services:
  registry:
    image: larrow/registry:2.6
    volumes:
      - /data/registry:/var/lib/registry
      - ./config/cert.pem:/etc/docker/registry/cert.pem
    env_file: config/env_file
    ports:
      - 5001:5001
  db:
    image: postgres
    ports:
      - 5433:5432
  redis:
    image: redis
    ports:
      - 6380:6379
  worker:
    build: worker
    volumes:
      - ./worker:/usr/src/app
      - ./config/private_key.pem:/usr/src/app/config/private_key.pem:ro
    env_file: config/env_file
    depends_on:
      - web
      - registry
      - redis
  web:
    build: .
    # useful for binding.pry and rails c
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      WEB_CONCURRENCY: 4
    env_file: config/env_file
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: larrow/caddy
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ./config/caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - registry
      - web
