version: '2'
services:
  registry:
    image: library/registry:2.4.0
    restart: always
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
  db:
    image: postgres
    ports:
      - 5433:5432
  redis:
    image: redis
    ports:
      - 6380:6379
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # sleep 3 seconds in order to wait db start up
    command: bash -c 'sleep 3 && bundle install && bundle exec sidekiq'
    environment:
      RAILS_ENV: development
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis/0
    volumes:
      - .:/shelter
    depends_on:
      - db
      - registry
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    # sleep 3 seconds in order to wait db start up
    command: bash -c 'sleep 3 && bundle install && bundle exec rake db:create db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0'
    environment:
      RAILS_ENV: development
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis/0
    volumes:
      - .:/shelter
    depends_on:
      - db
      - registry
  proxy:
    image: nginx:1.9
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - registry
      - web
