version: '2'
services:
  registry:
    image: library/registry:2.4.0
    restart: always
    volumes:
      - /data/registry:/storage
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
  db:
    image: postgres
    ports:
      - 5433:5432
  redis:
    image: redis
    ports:
      - 6380:6379
  worker:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: "backend"
    environment:
      RAILS_ENV: development
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis/0
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - registry
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    # useful for binding.pry and rails c
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis/0
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: nginx:1.9
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - registry
      - web
