version: "2"

services:
  registry:
    image: library/registry:2.4.0
    restart: always
    volumes:
      - ../config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
  db:
    image: postgres
  redis:
    image: redis
  worker:
    build: ..
    command: "backend"
    env_file: ../.env
    depends_on:
      - db
      - registry
      - redis
  web:
    build: ..
    env_file: ../.env
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: nginx:1.9
    restart: always
    volumes:
      - ../config/nginx:/etc/nginx
    depends_on:
      - db
      - registry
      - web
  test:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - proxy
