version: "2"

services:
  registry:
    image: library/registry:2.5.0
    volumes:
      - ../config/registry/root.crt:/etc/docker/registry/root.crt
      - ./config/registry/config.yml:/etc/docker/registry/config.yml
    environment:
      - GODEBUG=netdns=cgo
  db:
    image: postgres
  redis:
    image: redis
  worker:
    build: ../worker
    volumes:
      - ../config/private_key.pem:/usr/src/app/config/private_key.pem
    env_file: ../config/env_file
    depends_on:
      - web
      - registry
      - redis
  web:
    build: ..
    volumes:
      - ../config/private_key.pem:/usr/src/app/config/private_key.pem
    env_file: ../config/env_file
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: larrow/caddy
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ../config/caddy:/root/.caddy
    depends_on:
      - db
      - registry
      - web

  dind:
    image: docker:dind
    privileged: true
    command: "--insecure-registry proxy.local"
    volumes:
      - /var/run
    links:
      - proxy:proxy.local
  test:
    build: .
    volumes_from:
      - dind
    environment:
      remote_registry: 'proxy.local'
    depends_on:
      - dind
      - proxy
