version: '2'
services:
  registry:
    image: larrow/registry:2.6
    volumes:
      - ../config/cert.pem:/etc/docker/registry/cert.pem
    env_file: ../config/env_file
    environment:
      - REGISTRY_AUTH_TOKEN_REALM=http://proxy.local/service/token
  db:
    image: postgres
  redis:
    image: redis
  worker:
    build: ../worker
    volumes:
      - ../config/private_key.pem:/usr/src/app/config/private_key.pem
    env_file: ../config/env_file
    depends_on:
      - web
      - registry
      - redis
  web:
    build: ..
    volumes:
      - ../config/private_key.pem:/usr/src/app/config/private_key.pem
    env_file: ../config/env_file
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: larrow/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ../config/caddy:/root/.caddy
    depends_on:
      - db
      - registry
      - web

  dind:
    image: docker:dind
    privileged: true
    command: "--insecure-registry proxy.local"
    volumes:
      - /var/run
    links:
      - proxy:proxy.local
  test:
    build: .
    volumes_from:
      - dind
    environment:
      remote_registry: 'true'
    depends_on:
      - dind
      - proxy
