version: '2'
services:
  registry:
    image: larrow/registry:2.6
    volumes:
      - ./config/cert.pem:/etc/docker/registry/cert.pem
    env_file: config/env_file
  db:
    image: postgres
  redis:
    image: redis
  worker:
    image: larrow/shelter:worker
    volumes:
      - ./config/private_key.pem:/usr/src/app/config/private_key.pem
    env_file: config/env_file
    depends_on:
      - web
      - registry
      - redis
  web:
    image: larrow/shelter
    volumes:
      - ./config/private_key.pem:/usr/src/app/config/private_key.pem
    env_file: config/env_file
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: larrow/caddy
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ./config/caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - registry
      - web
