version: '2'
services:
  registry:
    image: library/registry:2.4.0
    volumes:
      - ./config/registry/:/etc/registry/
    environment:
      - GODEBUG=netdns=cgo
    ports:
      - 5001:5001
    command:
      ["serve", "/etc/registry/config.yml"]
  db:
    image: postgres
  redis:
    image: redis
  worker:
    image: larrow/shelter
    command: "backend"
    env_file: env_file
    depends_on:
      - db
      - registry
      - redis
  web:
    image: larrow/shelter
    env_file: env_file
    depends_on:
      - db
      - registry
      - redis
  proxy:
    image: nginx:1.9
    volumes:
      - ./config/nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - registry
      - web
