# config/app.yml for rails-settings-cached
defaults: &defaults
  registry_endpoint: http://proxy
  self_registration: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
